# Generated by Django 4.0.4 on 2022-04-22 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
