# Generated by Django 4.0.4 on 2022-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_firebase_id', models.CharField(max_length=250)),
            ],
        ),
    ]
